# This file was generated by GoReleaser. DO NOT EDIT.
cask "openbee" do
  version "0.0.40"

  on_macos do
    on_intel do
      sha256 "253292e531ba504383e8a9620820c4e6a995d4ab2808aca3038ac3c756869482"
      url "https://github.com/theopenbee/openbee/releases/download/v#{version}/openbee-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "901535313b8e67165ec7d28849af74913a6a0adb2a162033bba0f08ebed40468"
      url "https://github.com/theopenbee/openbee/releases/download/v#{version}/openbee-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d00a338568283e3d16014936f4f6db6eb52a4250553d586dd7ab5cbf36b6b3f4"
      url "https://github.com/theopenbee/openbee/releases/download/v#{version}/openbee-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "8c16f5e1f8184c1584662abd76f3ff22e871f0679bbb18d9a6f0df6700e69e84"
      url "https://github.com/theopenbee/openbee/releases/download/v#{version}/openbee-#{version}-linux-arm64.tar.gz"
    end
  end

  name "openbee"
  desc "OpenBee core service"
  homepage "https://github.com/theopenbee/openbee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openbee"

  # No zap stanza required

end
