# This file was generated by GoReleaser. DO NOT EDIT.
cask "openbee" do
  version "0.0.33"

  on_macos do
    on_intel do
      sha256 "06106833767a288647554225fc5806a2961f68f0aa4ed1e3ec3c905237d68ded"
      url "https://github.com/theopenbee/openbee/releases/download/v#{version}/openbee-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "e45d547d39e03c5fb6436cf9c07419a3b278019177231ee590b3fa1e40a66c03"
      url "https://github.com/theopenbee/openbee/releases/download/v#{version}/openbee-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24efe558d514b68955930fd8f4aaf00e0e2e0410866d0682f8aa4ed96f19ddd3"
      url "https://github.com/theopenbee/openbee/releases/download/v#{version}/openbee-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "8e345f6553704ec0400e409204926640f77410e2b1bfeb6b8cacf3552a64da84"
      url "https://github.com/theopenbee/openbee/releases/download/v#{version}/openbee-#{version}-linux-arm64.tar.gz"
    end
  end

  name "openbee"
  desc "OpenBee core service"
  homepage "https://github.com/theopenbee/openbee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openbee"

  # No zap stanza required

end
